<?php

/* main.js */
class __TwigTemplate_3125698418ac499ae85294003302df4d97d865efbd74f2e57a48697c1b6d29ba extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );

        $this->macros = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        // line 28
        echo "

/* gettext-compatible _ function, example of usage:
 *
 * > // Loading pl_PL.json here (containing polish translation strings generated by tools/i18n_compile.php)
 * > alert(_(\"Hello!\"));
 * Witaj!
 */
function _(s) {
\treturn (typeof l10n != 'undefined' && typeof l10n[s] != 'undefined') ? l10n[s] : s;
}

/* printf-like formatting function, example of usage:
 *
 * > alert(fmt(\"There are {0} birds on {1} trees\", [3,4]));
 * There are 3 birds on 4 trees
 * > // Loading pl_PL.json here (containing polish translation strings generated by tools/locale_compile.php)
 * > alert(fmt(_(\"{0} users\"), [3]));
 * 3 uzytkownikow
 */
function fmt(s,a) {
\treturn s.replace(/\\{([0-9]+)\\}/g, function(x) { return a[x[1]]; });
}

var saved = {};


var selectedstyle = '";
        echo addslashes($this->getAttribute($this->getAttribute((isset($context["config"]) ? $context["config"] : null), "default_stylesheet"), 0));
        // line 30
        echo "';
var styles = {
\t";
        echo "
\t";
        // line 31
        $context['_parent'] = (array) $context;
        $context['_seq'] = twig_ensure_traversable((isset($context["stylesheets"]) ? $context["stylesheets"] : null));
        foreach ($context['_seq'] as $context["_key"] => $context["stylesheet"]) {
            echo "'";
            echo addslashes($this->getAttribute((isset($context["stylesheet"]) ? $context["stylesheet"] : null), "name"));
            echo "' : '";
            echo addslashes($this->getAttribute((isset($context["stylesheet"]) ? $context["stylesheet"] : null), "uri"));
            // line 32
            echo "',
\t";
        }
        $_parent = $context['_parent'];
        unset($context['_seq'], $context['_iterated'], $context['_key'], $context['stylesheet'], $context['_parent'], $context['loop']);
        $context = array_intersect_key($context, $_parent) + $_parent;
        // line 37
        echo "
};
var board_name = false;

function changeStyle(styleName, link) {
\t";
        echo "
\t";
        // line 38
        if ($this->getAttribute((isset($context["config"]) ? $context["config"] : null), "stylesheets_board")) {
            // line 43
            echo "
\t\tif (board_name) {
\t\t\tstylesheet_choices[board_name] = styleName;
\t\t\tlocalStorage.board_stylesheets = JSON.stringify(stylesheet_choices);
\t\t}
\t";
        } else {
            // line 44
            echo "\t\tlocalStorage.stylesheet = styleName;
\t";
        }
        // line 46
        echo "\t";
        // line 76
        echo "
\t
\tif (!document.getElementById('stylesheet')) {
\t\tvar s = document.createElement('link');
\t\ts.rel = 'stylesheet';
\t\ts.type = 'text/css';
\t\ts.id = 'stylesheet';
\t\tvar x = document.getElementsByTagName('head')[0];
\t\tx.appendChild(s);
\t}
\t
\tdocument.getElementById('stylesheet').href = styles[styleName];
\tselectedstyle = styleName;
\t
\tif (document.getElementsByClassName('styles').length != 0) {
\t\tvar styleLinks = document.getElementsByClassName('styles')[0].childNodes;
\t\tfor (var i = 0; i < styleLinks.length; i++) {
\t\t\tstyleLinks[i].className = '';
\t\t}
\t}
\t
\tif (link) {
\t\tlink.className = 'selected';
\t}
\t
\tif (typeof \$ != 'undefined')
\t\t\$(window).trigger('stylesheet', styleName);
}


";
        echo "
";
        // line 77
        if ($this->getAttribute((isset($context["config"]) ? $context["config"] : null), "stylesheets_board")) {
            // line 78
            echo "\t";
            // line 79
            echo "\tvar matches = document.URL.match(/\\/(\\w+)\\/(\$|";
            echo strtr($this->getAttribute($this->getAttribute((isset($context["config"]) ? $context["config"] : null), "dir"), "res"), array("/" => "\\/"));
            echo strtr($this->getAttribute((isset($context["config"]) ? $context["config"] : null), "file_page"), array("%d" => "\\d+", "." => "\\."));
            echo "|";
            echo strtr($this->getAttribute((isset($context["config"]) ? $context["config"] : null), "file_index"), array("." => "\\."));
            echo "|";
            echo strtr($this->getAttribute((isset($context["config"]) ? $context["config"] : null), "file_page"), array("%d" => "\\d+", "." => "\\."));
            echo ")/);
\t";
            // line 98
            echo "
\tif (matches) {
\t\tboard_name = matches[1];
\t}
\t
\tif (!localStorage.board_stylesheets) {
\t\tlocalStorage.board_stylesheets = '{}';
\t}
\t
\tvar stylesheet_choices = JSON.parse(localStorage.board_stylesheets);
\tif (board_name && stylesheet_choices[board_name]) {
\t\tfor (var styleName in styles) {
\t\t\tif (styleName == stylesheet_choices[board_name]) {
\t\t\t\tchangeStyle(styleName);
\t\t\t\tbreak;
\t\t\t}
\t\t}
\t}
\t";
            echo "
";
        } else {
            // line 100
            echo "\t";
            // line 109
            echo "
\tif (localStorage.stylesheet) {
\t\tfor (var styleName in styles) {
\t\t\tif (styleName == localStorage.stylesheet) {
\t\t\t\tchangeStyle(styleName);
\t\t\t\tbreak;
\t\t\t}
\t\t}
\t}
\t";
            echo "
";
        }
        // line 163
        echo "

function init_stylechooser() {
\tvar newElement = document.createElement('div');
\tnewElement.className = 'styles';
\t
\tfor (styleName in styles) {
\t\tvar style = document.createElement('a');
\t\tstyle.innerHTML = '[' + styleName + ']';
\t\tstyle.onclick = function() {
\t\t\tchangeStyle(this.innerHTML.substring(1, this.innerHTML.length - 1), this);
\t\t};
\t\tif (styleName == selectedstyle) {
\t\t\tstyle.className = 'selected';
\t\t}
\t\tstyle.href = 'javascript:void(0);';
\t\tnewElement.appendChild(style);
\t}\t
\t
\tdocument.getElementsByTagName('body')[0].insertBefore(newElement, document.getElementsByTagName('body')[0].lastChild.nextSibling);
}

function get_cookie(cookie_name) {
\tvar results = document.cookie.match ( '(^|;) ?' + cookie_name + '=([^;]*)(;|\$)');
\tif (results)
\t\treturn (unescape(results[2]));
\telse
\t\treturn null;
}

function highlightReply(id) {
\tif (typeof window.event != \"undefined\" && event.which == 2) {
\t\t// don't highlight on middle click
\t\treturn true;
\t}
\t
\tvar divs = document.getElementsByTagName('div');
\tfor (var i = 0; i < divs.length; i++)
\t{
\t\tif (divs[i].className.indexOf('post') != -1)
\t\t\tdivs[i].className = divs[i].className.replace(/highlighted/, '');
\t}
\tif (id) {
\t\tvar post = document.getElementById('reply_'+id);
\t\tif (post)
\t\t\tpost.className += ' highlighted';
\t}
\treturn false;
}

function generatePassword() {
\tvar pass = '';
\tvar chars = '";
        echo $this->getAttribute((isset($context["config"]) ? $context["config"] : null), "genpassword_chars");
        // line 232
        echo "';
\tfor (var i = 0; i < 8; i++) {
\t\tvar rnd = Math.floor(Math.random() * chars.length);
\t\tpass += chars.substring(rnd, rnd + 1);
\t}
\treturn pass;
}

function dopost(form) {
\tif (form.elements['name']) {
\t\tlocalStorage.name = form.elements['name'].value.replace(/( |^)## .+\$/, '');
\t}
\tif (form.elements['password']) {
\t\tlocalStorage.password = form.elements['password'].value;
\t}
\tif (form.elements['email'] && form.elements['email'].value != 'sage') {
\t\tlocalStorage.email = form.elements['email'].value;
\t}
\t
\tsaved[document.location] = form.elements['body'].value;
\tsessionStorage.body = JSON.stringify(saved);
\t
\treturn form.elements['body'].value != \"\" || form.elements['file'].value != \"\" || (form.elements.file_url && form.elements['file_url'].value != \"\");
}

function citeReply(id, with_link) {
\tvar textarea = document.getElementById('body');
\t
\tif (document.selection) {
\t\t// IE
\t\ttextarea.focus();
\t\tvar sel = document.selection.createRange();
\t\tsel.text = '>>' + id + '\\n';
\t} else if (textarea.selectionStart || textarea.selectionStart == '0') {
\t\tvar start = textarea.selectionStart;
\t\tvar end = textarea.selectionEnd;
\t\ttextarea.value = textarea.value.substring(0, start) + '>>' + id + '\\n' + textarea.value.substring(end, textarea.value.length);
\t\t
\t\ttextarea.selectionStart += ('>>' + id).length + 1;
\t\ttextarea.selectionEnd = textarea.selectionStart;
\t} else {
\t\t// ???
\t\ttextarea.value += '>>' + id + '\\n';
\t}
\tif (typeof \$ != 'undefined') {
\t\t\$(window).trigger('cite', [id, with_link]);
\t\t\$(textarea).change();
\t}
\treturn false;
}

function rememberStuff() {
\tif (document.forms.post) {
\t\tif (document.forms.post.password) {
\t\t\tif (!localStorage.password)
\t\t\t\tlocalStorage.password = generatePassword();
\t\t\tdocument.forms.post.password.value = localStorage.password;
\t\t}
\t\t
\t\tif (localStorage.name && document.forms.post.elements['name'])
\t\t\tdocument.forms.post.elements['name'].value = localStorage.name;
\t\tif (localStorage.email && document.forms.post.elements['email'])
\t\t\tdocument.forms.post.elements['email'].value = localStorage.email;
\t\t
\t\tif (window.location.hash.indexOf('q') == 1)
\t\t\tciteReply(window.location.hash.substring(2), true);
\t\t
\t\tif (sessionStorage.body) {
\t\t\tvar saved = JSON.parse(sessionStorage.body);
\t\t\tif (get_cookie('";
        echo $this->getAttribute($this->getAttribute((isset($context["config"]) ? $context["config"] : null), "cookies"), "js");
        // line 234
        echo "')) {
\t\t\t\t// Remove successful posts
\t\t\t\tvar successful = JSON.parse(get_cookie('";
        echo $this->getAttribute($this->getAttribute((isset($context["config"]) ? $context["config"] : null), "cookies"), "js");
        // line 240
        echo "'));
\t\t\t\tfor (var url in successful) {
\t\t\t\t\tsaved[url] = null;
\t\t\t\t}
\t\t\t\tsessionStorage.body = JSON.stringify(saved);
\t\t\t\t
\t\t\t\tdocument.cookie = '";
        echo $this->getAttribute($this->getAttribute((isset($context["config"]) ? $context["config"] : null), "cookies"), "js");
        // line 293
        echo "={};expires=0;path=/;';
\t\t\t}
\t\t\tif (saved[document.location]) {
\t\t\t\tdocument.forms.post.body.value = saved[document.location];
\t\t\t}
\t\t}
\t\t
\t\tif (localStorage.body) {
\t\t\tdocument.forms.post.body.value = localStorage.body;
\t\t\tlocalStorage.body = '';
\t\t}
\t}
}

var script_settings = function(script_name) {
\tthis.script_name = script_name;
\tthis.get = function(var_name, default_val) {
\t\tif (typeof tb_settings == 'undefined' ||
\t\t\ttypeof tb_settings[this.script_name] == 'undefined' ||
\t\t\ttypeof tb_settings[this.script_name][var_name] == 'undefined')
\t\t\treturn default_val;
\t\treturn tb_settings[this.script_name][var_name];
\t}
};

function init() {
\tinit_stylechooser();
\t
\tif (document.forms.postcontrols) {
\t\tdocument.forms.postcontrols.password.value = localStorage.password;
\t}
\t
\tif (window.location.hash.indexOf('q') != 1 && window.location.hash.substring(1))
\t\thighlightReply(window.location.hash.substring(1));
}

var RecaptchaOptions = {
\ttheme : 'clean'
};

onready_callbacks = [];
function onready(fnc) {
\tonready_callbacks.push(fnc);
}

function ready() {
\tfor (var i = 0; i < onready_callbacks.length; i++) {
\t\tonready_callbacks[i]();
\t}
}

onready(init);

";
        if ($this->getAttribute((isset($context["config"]) ? $context["config"] : null), "google_analytics")) {
            // line 295
            echo "

var _gaq = _gaq || [];_gaq.push(['_setAccount', '";
            echo $this->getAttribute((isset($context["config"]) ? $context["config"] : null), "google_analytics");
            echo "']);";
            if ($this->getAttribute((isset($context["config"]) ? $context["config"] : null), "google_analytics_domain")) {
                echo "_gaq.push(['_setDomainName', '";
                echo $this->getAttribute((isset($context["config"]) ? $context["config"] : null), "google_analytics_domain");
                echo "'])";
            }
            if ((!$this->getAttribute((isset($context["config"]) ? $context["config"] : null), "google_analytics_domain"))) {
                echo "_gaq.push(['_setDomainName', 'none'])";
            }
            echo ";_gaq.push(['_trackPageview']);(function() {var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);})();";
        }
        // line 296
        echo "
";
    }

    public function getTemplateName()
    {
        return "main.js";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  398 => 296,  382 => 295,  326 => 293,  317 => 240,  312 => 234,  240 => 232,  185 => 163,  171 => 109,  169 => 100,  146 => 98,  136 => 79,  134 => 78,  132 => 77,  98 => 76,  96 => 46,  92 => 44,  84 => 43,  82 => 38,  73 => 37,  66 => 32,  58 => 31,  52 => 30,  22 => 28,);
    }
}
